### ISSUE TITLE
TypeError: read_git_blob() got an unexpected keyword argument 'root'

### ISSUE THREAD

**Issue by geromueller** [jonathansick/preprint#14]
I get the following error when doing "preprint watch --diff"
git version 2.5.0, Archlinux

Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/gmueller/python/lib/python2.7/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/home/gmueller/python/lib/python2.7/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/home/gmueller/python/lib/python2.7/site-packages/watchdog/events.py", line 322, in dispatch
    self.on_any_event(event)
  File "/home/gmueller/python/lib/python2.7/site-packages/preprint/watch.py", line 82, in on_any_event
    self.run_compile()
  File "/home/gmueller/python/lib/python2.7/site-packages/preprint/watch.py", line 114, in run_compile
    self._prev_commit)
  File "/home/gmueller/python/lib/python2.7/site-packages/preprint/latexdiff.py", line 55, in git_diff_pipeline
    prev_path = inline_prev(prev_commit, master_path)
  File "/home/gmueller/python/lib/python2.7/site-packages/preprint/latexdiff.py", line 124, in inline_prev
    root=git_root)
TypeError: read_git_blob() got an unexpected keyword argument 'root'

**Comment by geromueller** [comment]
change root= to repo_dir=
